### ISSUE TITLE
in and out subdirectories missing?

### ISSUE THREAD

**Issue by zvada** [CMSCompOps/AAAOps#2]
Do we have incomplete move here or why "in" and "out" subdirectories are missing?

**Comment by EnginEren** [comment]
On purpose, I did not put them since we have only txt and json files there (which are very very important though). I can put them if you want. Do we need them?

**Comment by zvada** [comment]
I think we should keep them as long as we reference in the code $FEDINFO/in/ and $FEDINFO/out/. It should be also documented in the .md file. We could also improve the code and get rid of "in" and "out" and use variables instead. But for now it's not worth effort so we should upload in/out as well.

**Comment by EnginEren** [comment]
Hi Marian,

I have put them.
Engin

**Comment by zvada** [comment]
OK, I see it in Dev branch. Let's push it to prod then. Thanks, closing...
