### ISSUE TITLE
StorageBackend script usage

### ISSUE THREAD

**Issue by zvada** [CMSCompOps/AAAOps#5]
@EnginEren: could you document usage of more cases than DPM only, please?

**Comment by zvada** [comment]
Refering to: https://github.com/CMSCompOps/AAAOps/blob/master/StorageBackend/README.md

**Comment by EnginEren** [comment]
Hi Marian,

I updated. How is it now ?

https://github.com/CMSCompOps/AAAOps/blob/master/StorageBackend/README.md

**Comment by zvada** [comment]
I did few edits, I think we can close this as resolved. Thanks.
