### ISSUE TITLE
Allow list for EU region

### ISSUE THREAD

**Issue by EnginEren** [CMSCompOps/AAAOps#6]
Dear all,

We need to be careful while preparing allow list for EU region. For example, UK sites. They all come from "ac.uk" domain. If we do like this : 

*.ac.uk 

We cannot know whether this is brunel or imperial collage etc.. That's why, best way to do it : 

*.bris.ac.uk
*.brunel.ac.uk
*.ic.ac.uk
*.rl.ac.uk

UK is one example. Other guys I have spotted are "in2p3.fr", "infn.it", "cern.ch". In total, we have 4 exception. 

My algorithm is the following : 
1-Write one extra sub-domain name for these 4 exceptional sites. (i.e *brunel.ac.uk)
2-For others, always use 2-word domain name (i.e *desy.de, *gridka.de etc..)

That is basically what I have done here [1]

Cheers,
Engin

[1] https://github.com/CMSCompOps/AAAOps/blob/Dev/Federation/out/list_eu_better.allow

**Comment by zvada** [comment]
From generated list, these are really hostnames, not domains for the whitelist (ignore `*.`, wanted to show example these shouldn't be treated the way they are):

*.ccxrpli003.in2p3.fr
*.llrpp01.in2p3.fr
*.llrxrd-redir.in2p3.fr
*.polgrid4.in2p3.fr
*.sbgse1.in2p3.fr
*.roma1.infn.it
*.eoscms-srv-b2.cern.ch
*.eoscms-srv-m1.cern.ch
*.p05614910m96330.cern.ch
*.xrdcmstzero1.cern.ch
*.xrdcmstzero2.cern.ch
*.xrdcmstzero3.cern.ch

Could you take a look?

Thanks,
Marian

**Comment by EnginEren** [comment]
Hi Marian,

Yes. I know. It is 5s to reduce this list into : 

*in2p3.fr
*infn.it
*cern.ch

But how do we differentiate (for example) llrpp01.in2p3.fr (T2_FR_GRIF_LLR) from sbgse1.in2p3.fr (T2_FR_IPHC) ?? 

Imagine T2_FR_IPHC has some problems and we want to remove it from white list.. What do we do ? If we remove *in2p3.fr, all french sites are gone.

What do you think?

Cheers,
Engin

**Comment by zvada** [comment]
Hi Engin,

I wouldn't worry much about differentiation for such case because if we know troublesome hostname we don't need to touch `cms.whitelist`. Along that we'll be enabling `cms.blacklist` which will be the place for malicious hostnames, example of the config here: http://t2.unl.edu/store/zvada/xrootd-configs/cms.blacklist.

So the xrootd config of EU redirectors will include the two lines:
```
cms.whitelist /etc/xrootd/cms.whitelist
cms.blacklist /etc/xrootd/cms.blacklist
```

Therefore, all we need for default `cms.whitelist` is make sure we have in the list just `*.<domain>` format without real hostnames. We still need special cases to differentiate `CMS site name` versus domain/hostas in the Site Status Board where do you mapping based on VO feed but that's unrelated to the whitelist code and you have that under control, right?

Hope that helps.

Thanks,
Marian

**Comment by EnginEren** [comment]
Hi Marian (sorry for late reply),

Okay. Just to understand : When do we touch allow list then ? What is the purpose of whilelist ? 

And yes, input from VO feed is almost under-control. Sometimes we see interesting host names and we ask directly to the sites.
Cheers,
Engin

**Comment by zvada** [comment]
We touch allow list when we want to disable particular domain out of production federation. Don't mix whilelist and blacklist, blacklist is really just for exactly rare case when we have domain name which involves e.g. two sitenames so then we can have domain in whitelist but can disable particular host of the site in the blacklist when needed.

If you're confused or something is unclear we should rediscuss over chat.

Thanks,
Marian

**Comment by EnginEren** [comment]
Hi Marian,

Thanks Marian. I have done it as you wanted. Here [1]. 

Cheers,
Engin


[1] https://github.com/CMSCompOps/AAAOps/blob/Dev/Federation/out/list_eu.allow

**Comment by EnginEren** [comment]
Hi Marian again,

Based on what we have discussed in Slack, I have parsed another allow list [1]. I'm waiting for your comments.

Cheers,
Engin

[1] https://github.com/CMSCompOps/AAAOps/blob/Dev/Federation/out/list_eu_final.allow

**Comment by zvada** [comment]
This looks good to me! Please, do PR move this to production master branch.

Thanks,
Marian

**Comment by zvada** [comment]
Closing, this has moved to PR: https://github.com/CMSCompOps/AAAOps/pull/7
